function liste = generate_list_of_structures_for_analysis(rig)



liste.ethogramme = {'t','neuron', 'stimuli', 'pipeline', 'protocol', 'run',...
    'cast', 'stop', 'hunch', 'back', 'roll'};

liste.ensemble_averaged_behaviours = {'t','neuron', 'stimuli', 'pipeline', 'protocol', 'run',...
    'cast', 'stop', 'hunch', 'back', 'roll'};


liste.transition = {'t','neuron', 'stimuli', 'pipeline', 'protocol', 'global_state'};


liste.first_part = {'t','neuron', 'stimuli', 'pipeline', 'protocol', 'run',...
    'cast', 'stop', 'hunch', 'back', 'roll','global_state', 't_start_stop',...
    'pure_motion_velocity_25', 'S_smooth_10', 'pure_deriv_S_norm_10', 'larva_length', ...
    'x_head', 'y_head', 'x_tail', 'y_tail', 'x_center', 'y_center', 'S', 'x_neck_top', 'y_neck_top', ...
    'x_neck_down', 'y_neck_down', 'x_neck', 'y_neck'};

% liste.first_part = {'t','neuron', 'stimuli', 'pipeline', 'protocol', 'run',...
%     'cast', 'stop', 'hunch', 'back', 'roll','global_state', 't_start_stop',...
%     'pure_motion_velocity_25', 'S_smooth_10', 'pure_deriv_S_norm_10', 'larva_length', 'S', ...
%      'x_head', 'y_head', 'x_tail', 'y_tail', 'x_center', 'y_center'};



end